<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

	<xacro:include filename="xacro_macro.xacro" />

	<!-- # set parameters -->
	<xacro:property name="chassis_length" value="0.35" />
	<xacro:property name="chassis_width" value="0.35" />
	<xacro:property name="chassis_height" value="0.10" />
	<xacro:property name="chassis_mass" value="10" />

	<xacro:property name="caster_hub_mass" value="0.2" />
	<xacro:property name="caster_hub_radius" value="0.02" />
	<xacro:property name="caster_hub_length" value="0.04" />
	<xacro:property name="wheel_radius" value="0.03" />
	<xacro:property name="wheel_length" value="0.02" />
	<xacro:property name="wheel_mass" value="0.1" />

	<!-- # base_link -->
	<link name="base_link" />

	<!-- # base_footprint link -->
	<joint name="base_footprint_joint" type="fixed">
		<parent link="base_link" />
		<child link="base_footprint" />
		<origin xyz="0 0 0" rpy="0 0 0" />
	</joint>

	<link name="base_footprint" />

	<!-- # chassis link -->
	<joint name="chassis_joint" type="fixed">
		<parent link="base_link" />
		<child link="chassis" />
		<origin xyz="0 0 0" />
	</joint>

	<xacro:link_generator name="chassis" color_name="orange"
		origin_x="0" 
		origin_y="0"
		origin_z="${chassis_height/2}"
		mass="${chassis_mass}">

		<box size="${chassis_length} ${chassis_width} ${chassis_height}" />

		<xacro:inertial_box
			mass="${chassis_mass}"
			x="${chassis_length}"
			y="${chassis_width}"
			z="${chassis_height}" />	
	</xacro:link_generator>

	<gazebo reference="chassis">
		<material>Gazebo/Orange</material>
	</gazebo>

	<!-- front_left_steer_hub link -->
	<joint name="front_left_steer_hub_joint" type="continuous">
		<parent link="base_link" />
		<child link="front_left_steer_hub_link" />
		<origin
			xyz="${chassis_length/2-caster_hub_radius} ${chassis_width/2-caster_hub_radius} 0" />
		<axis xyz="0 0 1" />
	</joint>
	
	<xacro:link_generator name="front_left_steer_hub_link" color_name="white"
		origin_x="0"
		origin_y="0"
		origin_z="${-caster_hub_length/2}"
		mass="${caster_hub_mass}">

		<cylinder radius="${caster_hub_radius}" length="${caster_hub_length}" />

		<xacro:inertial_cylinder
			mass="${caster_hub_mass}"
			length="${caster_hub_length}"
			radius="${caster_hub_radius}" />
	</xacro:link_generator>

	<gazebo reference="chassis">
		<material>Gazebo/White</material>
	</gazebo>

	<!-- front_left_wheel link -->
	<joint name="front_left_drive_wheel_joint" type="continuous">
		<parent link="front_left_steer_hub_link" />
		<child link="front_left_drive_wheel_link" />
		<origin xyz="${-caster_hub_radius} 0 ${-caster_hub_length}"
			rpy="${pi/2} 0 0" />
		<axis xyz="0 0 1" />
	</joint>

	<xacro:link_generator name="front_left_drive_wheel_link" color_name="black"
		origin_x="0"
		origin_y="0"
		origin_z="0"
		mass="${wheel_mass}">

		<cylinder radius="${wheel_radius}" length="${wheel_length}" />

		<xacro:inertial_cylinder
			mass="${wheel_mass}"
			length="${wheel_length}"
			radius="${wheel_radius}" />
	</xacro:link_generator>

	<gazebo reference="chassis">
		<material>Gazebo/Black</material>
	</gazebo>

	<!-- front_right_steer_hub link -->
	<joint name="front_right_steer_hub_joint" type="continuous">
		<parent link="base_link" />
		<child link="front_right_steer_hub_link" />
		<origin
			xyz="${chassis_length/2-caster_hub_radius} ${-chassis_width/2+caster_hub_radius} 0" />
		<axis xyz="0 0 1" />
	</joint>

	<xacro:link_generator name="front_right_steer_hub_link" color_name="white"
		origin_x="0"
		origin_y="0"
		origin_z="${-caster_hub_length/2}"
		mass="${caster_hub_mass}">

		<cylinder radius="${caster_hub_radius}" length="${caster_hub_length}" />

		<xacro:inertial_cylinder
			mass="${caster_hub_mass}"
			length="${caster_hub_length}"
			radius="${caster_hub_radius}" />
	</xacro:link_generator>

	<gazebo reference="chassis">
		<material>Gazebo/White</material>
	</gazebo>

	<!-- front_right_wheel link -->
	<joint name="front_right_drive_wheel_joint" type="continuous">
		<parent link="front_right_steer_hub_link" />
		<child link="front_right_drive_wheel_link" />
		<origin xyz="${-caster_hub_radius} 0 ${-caster_hub_length}"
			rpy="${pi/2} 0 0" />
		<axis xyz="0 0 1" />
	</joint>

	<xacro:link_generator name="front_right_drive_wheel_link" color_name="black"
		origin_x="0"
		origin_y="0"
		origin_z="0"
		mass="${wheel_mass}">

		<cylinder radius="${wheel_radius}" length="${wheel_length}" />

		<xacro:inertial_cylinder
			mass="${wheel_mass}"
			length="${wheel_length}"
			radius="${wheel_radius}" />
	</xacro:link_generator>

	<gazebo reference="chassis">
		<material>Gazebo/Black</material>
	</gazebo>

	<!-- back_right_steer_hub link -->
	<joint name="back_right_steer_hub_joint" type="continuous">
		<parent link="base_link" />
		<child link="back_right_steer_hub_link" />
		<origin
			xyz="${-chassis_length/2+caster_hub_radius} ${-chassis_width/2+caster_hub_radius} 0" />
		<axis xyz="0 0 1" />
	</joint>

	<xacro:link_generator name="back_right_steer_hub_link" color_name="white"
		origin_x="0"
		origin_y="0"
		origin_z="${-caster_hub_length/2}"
		mass="${caster_hub_mass}">

		<cylinder radius="${caster_hub_radius}" length="${caster_hub_length}" />

		<xacro:inertial_cylinder
			mass="${caster_hub_mass}"
			length="${caster_hub_length}"
			radius="${caster_hub_radius}" />
	</xacro:link_generator>

	<gazebo reference="chassis">
		<material>Gazebo/White</material>
	</gazebo>

	<!-- back_right_wheel link -->
	<joint name="back_right_drive_wheel_joint" type="continuous">
		<parent link="back_right_steer_hub_link" />
		<child link="back_right_drive_wheel_link" />
		<origin xyz="${-caster_hub_radius} 0 ${-caster_hub_length}"
			rpy="${pi/2} 0 0" />
		<axis xyz="0 0 1" />
	</joint>

	<xacro:link_generator name="back_right_drive_wheel_link" color_name="black"
		origin_x="0"
		origin_y="0"
		origin_z="0"
		mass="${wheel_mass}">

		<cylinder radius="${wheel_radius}" length="${wheel_length}" />

		<xacro:inertial_cylinder
			mass="${wheel_mass}"
			length="${wheel_length}"
			radius="${wheel_radius}" />
	</xacro:link_generator>

	<gazebo reference="chassis">
		<material>Gazebo/Black</material>
	</gazebo>

	<!-- back_left_steer_hub link -->
	<joint name="back_left_steer_hub_joint" type="continuous">
		<parent link="base_link" />
		<child link="back_left_steer_hub_link" />
		<origin
			xyz="${-chassis_length/2+caster_hub_radius} ${chassis_width/2-caster_hub_radius} 0" />
		<axis xyz="0 0 1" />
	</joint>

	<xacro:link_generator name="back_left_steer_hub_link" color_name="white"
		origin_x="0"
		origin_y="0"
		origin_z="${-caster_hub_length/2}"
		mass="${caster_hub_mass}">

		<cylinder radius="${caster_hub_radius}" length="${caster_hub_length}" />

		<xacro:inertial_cylinder
			mass="${caster_hub_mass}"
			length="${caster_hub_length}"
			radius="${caster_hub_radius}" />
	</xacro:link_generator>

	<gazebo reference="chassis">
		<material>Gazebo/White</material>
	</gazebo>
	
	<!-- back_left_wheel link -->
	<joint name="back_left_drive_wheel_joint" type="continuous">
		<parent link="back_left_steer_hub_link" />
		<child link="back_left_drive_wheel_link" />
		<origin xyz="${-caster_hub_radius} 0 ${-caster_hub_length}"
			rpy="${pi/2} 0 0" />
		<axis xyz="0 0 1" />
	</joint>

	<xacro:link_generator name="back_left_drive_wheel_link" color_name="black"
		origin_x="0"
		origin_y="0"
		origin_z="0"
		mass="${wheel_mass}">

		<cylinder radius="${wheel_radius}" length="${wheel_length}" />

		<xacro:inertial_cylinder
			mass="${wheel_mass}"
			length="${wheel_length}"
			radius="${wheel_radius}" />
	</xacro:link_generator>

	<gazebo reference="chassis">
		<material>Gazebo/Black</material>
	</gazebo>
</robot>