<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

	<xacro:include filename="swervebot_macro.xacro" />

	<!-- set parameters -->
	<xacro:property name="chassis_length" value="0.35" />
	<xacro:property name="chassis_width" value="0.35" />
	<xacro:property name="chassis_height" value="0.10" />
	<xacro:property name="chassis_mass" value="10" />

	<xacro:property name="caster_hub_mass" value="0.2" />
	<xacro:property name="caster_hub_radius" value="0.02" />
	<xacro:property name="caster_hub_length" value="0.04" />
	<xacro:property name="wheel_radius" value="0.03" />
	<xacro:property name="wheel_length" value="0.02" />
	<xacro:property name="wheel_mass" value="0.1" />

	<!-- base_link -->
	<link name="base_link" />

	<!-- base_footprint link -->
	<joint name="base_footprint_joint" type="fixed">
		<parent link="base_link" />
		<child link="base_footprint" />
		<origin xyz="0 0 0" rpy="0 0 0" />
	</joint>

	<link name="base_footprint" />

	<!-- chassis link -->
	<joint name="chassis_joint" type="fixed">
		<parent link="base_link" />
		<child link="chassis" />
		<origin xyz="0 0 0" />
	</joint>

	<xacro:link_generator name="chassis" color_name="orange"
		origin_x="0"
		origin_y="0"
		origin_z="${chassis_height/2}"
		mass="${chassis_mass}">

		<box size="${chassis_length} ${chassis_width} ${chassis_height}" />

		<xacro:inertial_box
			mass="${chassis_mass}"
			x="${chassis_length}"
			y="${chassis_width}"
			z="${chassis_height}" />
	</xacro:link_generator>

	<gazebo reference="chassis">
		<material>Gazebo/Orange</material>
	</gazebo>

	<!-- steering_front_left link -->
	<joint name="steering_front_left_joint" type="continuous">
		<parent link="base_link" />
		<child link="steering_front_left_link" />
		<origin
			xyz="${chassis_length/2-caster_hub_radius} ${chassis_width/2-caster_hub_radius} 0" />
		<axis xyz="0 0 1" />
	</joint>

	<xacro:link_generator name="steering_front_left_link" color_name="white"
		origin_x="0"
		origin_y="0"
		origin_z="${-caster_hub_length/2}"
		mass="${caster_hub_mass}">

		<cylinder radius="${caster_hub_radius}" length="${caster_hub_length}" />

		<xacro:inertial_cylinder
			mass="${caster_hub_mass}"
			length="${caster_hub_length}"
			radius="${caster_hub_radius}" />
	</xacro:link_generator>

	<gazebo reference="chassis">
		<material>Gazebo/White</material>
	</gazebo>

	<!-- driving_front_left link -->
	<joint name="driving_front_left_joint" type="continuous">
		<parent link="steering_front_left_link" />
		<child link="driving_front_left_link" />
		<origin xyz="${-caster_hub_radius} 0 ${-caster_hub_length}"
			rpy="${pi/2} 0 0" />
		<axis xyz="0 0 1" />
	</joint>

	<xacro:link_generator name="driving_front_left_link" color_name="black"
		origin_x="0"
		origin_y="0"
		origin_z="0"
		mass="${wheel_mass}">

		<cylinder radius="${wheel_radius}" length="${wheel_length}" />

		<xacro:inertial_cylinder
			mass="${wheel_mass}"
			length="${wheel_length}"
			radius="${wheel_radius}" />
	</xacro:link_generator>

	<gazebo reference="chassis">
		<material>Gazebo/Black</material>
	</gazebo>

	<!-- steering_front_right link -->
	<joint name="steering_front_right_joint" type="continuous">
		<parent link="base_link" />
		<child link="steering_front_right_link" />
		<origin
			xyz="${chassis_length/2-caster_hub_radius} ${-chassis_width/2+caster_hub_radius} 0" />
		<axis xyz="0 0 1" />
	</joint>

	<xacro:link_generator name="steering_front_right_link" color_name="white"
		origin_x="0"
		origin_y="0"
		origin_z="${-caster_hub_length/2}"
		mass="${caster_hub_mass}">

		<cylinder radius="${caster_hub_radius}" length="${caster_hub_length}" />

		<xacro:inertial_cylinder
			mass="${caster_hub_mass}"
			length="${caster_hub_length}"
			radius="${caster_hub_radius}" />
	</xacro:link_generator>

	<gazebo reference="chassis">
		<material>Gazebo/White</material>
	</gazebo>

	<!-- driving_front_right link -->
	<joint name="driving_front_right_joint" type="continuous">
		<parent link="steering_front_right_link" />
		<child link="driving_front_right_link" />
		<origin xyz="${-caster_hub_radius} 0 ${-caster_hub_length}"
			rpy="${pi/2} 0 0" />
		<axis xyz="0 0 1" />
	</joint>

	<xacro:link_generator name="driving_front_right_link" color_name="black"
		origin_x="0"
		origin_y="0"
		origin_z="0"
		mass="${wheel_mass}">

		<cylinder radius="${wheel_radius}" length="${wheel_length}" />

		<xacro:inertial_cylinder
			mass="${wheel_mass}"
			length="${wheel_length}"
			radius="${wheel_radius}" />
	</xacro:link_generator>

	<gazebo reference="chassis">
		<material>Gazebo/Black</material>
	</gazebo>

	<!-- steering_rear_right link -->
	<joint name="steering_rear_right_joint" type="continuous">
		<parent link="base_link" />
		<child link="steering_rear_right_link" />
		<origin
			xyz="${-chassis_length/2+caster_hub_radius} ${-chassis_width/2+caster_hub_radius} 0" />
		<axis xyz="0 0 1" />
	</joint>

	<xacro:link_generator name="steering_rear_right_link" color_name="white"
		origin_x="0"
		origin_y="0"
		origin_z="${-caster_hub_length/2}"
		mass="${caster_hub_mass}">

		<cylinder radius="${caster_hub_radius}" length="${caster_hub_length}" />

		<xacro:inertial_cylinder
			mass="${caster_hub_mass}"
			length="${caster_hub_length}"
			radius="${caster_hub_radius}" />
	</xacro:link_generator>

	<gazebo reference="chassis">
		<material>Gazebo/White</material>
	</gazebo>

	<!-- driving_rear_right link -->
	<joint name="driving_rear_right_joint" type="continuous">
		<parent link="steering_rear_right_link" />
		<child link="driving_rear_right_link" />
		<origin xyz="${-caster_hub_radius} 0 ${-caster_hub_length}"
			rpy="${pi/2} 0 0" />
		<axis xyz="0 0 1" />
	</joint>

	<xacro:link_generator name="driving_rear_right_link" color_name="black"
		origin_x="0"
		origin_y="0"
		origin_z="0"
		mass="${wheel_mass}">

		<cylinder radius="${wheel_radius}" length="${wheel_length}" />

		<xacro:inertial_cylinder
			mass="${wheel_mass}"
			length="${wheel_length}"
			radius="${wheel_radius}" />
	</xacro:link_generator>

	<gazebo reference="chassis">
		<material>Gazebo/Black</material>
	</gazebo>

	<!-- steering_rear_left link -->
	<joint name="steering_rear_left_joint" type="continuous">
		<parent link="base_link" />
		<child link="steering_rear_left_link" />
		<origin
			xyz="${-chassis_length/2+caster_hub_radius} ${chassis_width/2-caster_hub_radius} 0" />
		<axis xyz="0 0 1" />
	</joint>

	<xacro:link_generator name="steering_rear_left_link" color_name="white"
		origin_x="0"
		origin_y="0"
		origin_z="${-caster_hub_length/2}"
		mass="${caster_hub_mass}">

		<cylinder radius="${caster_hub_radius}" length="${caster_hub_length}" />

		<xacro:inertial_cylinder
			mass="${caster_hub_mass}"
			length="${caster_hub_length}"
			radius="${caster_hub_radius}" />
	</xacro:link_generator>

	<gazebo reference="chassis">
		<material>Gazebo/White</material>
	</gazebo>

	<!-- driving_rear_left link -->
	<joint name="driving_rear_left_joint" type="continuous">
		<parent link="steering_rear_left_link" />
		<child link="driving_rear_left_link" />
		<origin xyz="${-caster_hub_radius} 0 ${-caster_hub_length}"
			rpy="${pi/2} 0 0" />
		<axis xyz="0 0 1" />
	</joint>

	<xacro:link_generator name="driving_rear_left_link" color_name="black"
		origin_x="0"
		origin_y="0"
		origin_z="0"
		mass="${wheel_mass}">

		<cylinder radius="${wheel_radius}" length="${wheel_length}" />

		<xacro:inertial_cylinder
			mass="${wheel_mass}"
			length="${wheel_length}"
			radius="${wheel_radius}" />
	</xacro:link_generator>

	<gazebo reference="chassis">
		<material>Gazebo/Black</material>
	</gazebo>
</robot>