controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    caster_swerve_drive_controller:
      type: caster_swerve_drive_controller/CasterSwerveDriveController
    feedforward_controller_steering_front_left_joint:
      type: pid_controller/PidController

feedforward_controller_steering_front_left_joint:
  ros__parameters:
    dof_names:
      - steering_front_left_joint

    command_interface: position

    reference_and_state_interfaces: 
      - position

    gains:
      steering_front_left_joint: {p: 1.0}

caster_swerve_drive_controller:
  ros__parameters:
    steering_joint_names:
     - feedforward_controller_steering_front_left_joint/steering_front_left_joint
     - steering_front_right_joint
     - steering_rear_left_joint
     - steering_rear_right_joint

