controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    caster_swerve_drive_controller:
      type: caster_swerve_drive_controller/CasterSwerveDriveController